export const ORGANIZATION_CHANGED_TOPIC = 'ORGANIZATION_CHANGED';
export const GUIDE_CHANGED_TOPIC = 'GUIDE_CHANGED';
export const AVAILABLE_QUESTS_CHANGED_TOPIC = 'AVAILABLE_QUESTS_CHANGED';
export const ADMIN_EVENT_TOPIC = 'ADMIN_EVENT_TOPIC';
export const AVAILABLE_GUIDES_CHANGED_TOPIC = 'AVAILABLE_GUIDES_CHANGED';

export const STEP_AUTO_COMPLETE_INTERACTIONS_CHANGED_TOPIC =
  'STEP_AUTO_COMPLETE_INTERACTIONS_CHANGED';
export const GUIDE_BASE_CHANGED_TOPIC = 'GUIDE_BASE_CHANGED';
export const ORGANIZATION_INLINE_EMBEDS_CHANGED_TOPIC =
  'ORGANIZATION_INLINE_EMBEDS_CHANGED';
export const ONBOARDING_INLINE_EMBEDS_CHANGED_TOPIC =
  'ONBOARDING_INLINE_EMBEDS_CHANGED';
export const TEMPLATE_INLINE_EMBED_CHANGED_TOPIC =
  'TEMPLATE_INLINE_EMBED_CHANGED';
export const ACCOUNT_USER_INLINE_EMBEDS_CHANGED_TOPIC =
  'ACCOUNT_USER_INLINE_EMBEDS_CHANGED';
